"""add close_reason to game_sessions

Revision ID: 3f76080cb276
Revises: c458adb985fb
Create Date: 2026-09-08 12:13:05.007963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f76080cb276'
down_revision: Union[str, None] = 'c458adb985fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('close_reason', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'close_reason')
    # ### end Alembic commands ###
