"""initial schema

Revision ID: c458adb985fb
Revises: 
Create Date: 2026-09-01 18:35:53.518104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c458adb985fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dofirstshot', sa.Boolean(), nullable=True),
    sa.Column('turn', sa.String(length=16), nullable=False),
    sa.Column('pending_shot', sa.String(length=3), nullable=True),
    sa.Column('ships', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('own_hits', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_sessions_active', 'game_sessions', ['status'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_table('shots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('coordinate', sa.String(length=3), nullable=False),
    sa.Column('result', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_shots_session_id_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shots')
    op.drop_index('ix_game_sessions_active', table_name='game_sessions', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
